//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "event_list")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_year: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_code: String,
    #[sea_orm(column_type = "Text")]
    pub alias: String,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    #[sea_orm(has_many)]
    pub match_data: HasMany<super::match_data::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

