//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "external_store")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_type: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub request: String,
    #[sea_orm(column_type = "Text")]
    pub data: String,
    #[sea_orm(ignore, column_type = "custom(\"DATETIME\")", select_as = "text")]
    pub last_modified: String,
}

impl ActiveModelBehavior for ActiveModel {}
