//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "match_list")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_year: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_code: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub team_key: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub match_key: String,
    #[sea_orm(column_type = "Text")]
    pub assigned_user_id: String,
}

impl ActiveModelBehavior for ActiveModel {}
