//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "team_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub event_year: i64,
    #[sea_orm(column_type = "Text")]
    pub event_code: String,
    #[sea_orm(column_type = "Text")]
    pub team_key: String,
    #[sea_orm(column_type = "Text")]
    pub data: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub inflight: bool,
    #[sea_orm(ignore, column_type = "custom(\"DATETIME\")", select_as = "text")]
    pub last_modified: String,
    #[sea_orm(
        belongs_to,
        from = "(event_year, event_code, team_key)",
        to = "(event_year, event_code, team_key)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub team_list: HasOne<super::team_list::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

