/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyRouteImport } from "./routes/verify"
import { Route as ResetRouteImport } from "./routes/reset"
import { Route as PitscoutRouteImport } from "./routes/pitscout"
import { Route as PitRouteImport } from "./routes/pit"
import { Route as MatchRouteImport } from "./routes/match"
import { Route as HomeRouteImport } from "./routes/home"
import { Route as EventsRouteImport } from "./routes/events"
import { Route as AuthRouteImport } from "./routes/auth"
import { Route as IndexRouteImport } from "./routes/index"

const VerifyRoute = VerifyRouteImport.update({
  id: "/verify",
  path: "/verify",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: "/reset",
  path: "/reset",
  getParentRoute: () => rootRouteImport,
} as any)
const PitscoutRoute = PitscoutRouteImport.update({
  id: "/pitscout",
  path: "/pitscout",
  getParentRoute: () => rootRouteImport,
} as any)
const PitRoute = PitRouteImport.update({
  id: "/pit",
  path: "/pit",
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: "/match",
  path: "/match",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/events": typeof EventsRoute
  "/home": typeof HomeRoute
  "/match": typeof MatchRoute
  "/pit": typeof PitRoute
  "/pitscout": typeof PitscoutRoute
  "/reset": typeof ResetRoute
  "/verify": typeof VerifyRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/events": typeof EventsRoute
  "/home": typeof HomeRoute
  "/match": typeof MatchRoute
  "/pit": typeof PitRoute
  "/pitscout": typeof PitscoutRoute
  "/reset": typeof ResetRoute
  "/verify": typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/events": typeof EventsRoute
  "/home": typeof HomeRoute
  "/match": typeof MatchRoute
  "/pit": typeof PitRoute
  "/pitscout": typeof PitscoutRoute
  "/reset": typeof ResetRoute
  "/verify": typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/auth"
    | "/events"
    | "/home"
    | "/match"
    | "/pit"
    | "/pitscout"
    | "/reset"
    | "/verify"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/auth"
    | "/events"
    | "/home"
    | "/match"
    | "/pit"
    | "/pitscout"
    | "/reset"
    | "/verify"
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/events"
    | "/home"
    | "/match"
    | "/pit"
    | "/pitscout"
    | "/reset"
    | "/verify"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  HomeRoute: typeof HomeRoute
  MatchRoute: typeof MatchRoute
  PitRoute: typeof PitRoute
  PitscoutRoute: typeof PitscoutRoute
  ResetRoute: typeof ResetRoute
  VerifyRoute: typeof VerifyRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify": {
      id: "/verify"
      path: "/verify"
      fullPath: "/verify"
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset": {
      id: "/reset"
      path: "/reset"
      fullPath: "/reset"
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pitscout": {
      id: "/pitscout"
      path: "/pitscout"
      fullPath: "/pitscout"
      preLoaderRoute: typeof PitscoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pit": {
      id: "/pit"
      path: "/pit"
      fullPath: "/pit"
      preLoaderRoute: typeof PitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/match": {
      id: "/match"
      path: "/match"
      fullPath: "/match"
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/home": {
      id: "/home"
      path: "/home"
      fullPath: "/home"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/events": {
      id: "/events"
      path: "/events"
      fullPath: "/events"
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  HomeRoute: HomeRoute,
  MatchRoute: MatchRoute,
  PitRoute: PitRoute,
  PitscoutRoute: PitscoutRoute,
  ResetRoute: ResetRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
