/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthIndexRouteRouteImport } from "./routes/auth/index.route";
import { Route as AuthComponentsLoadWidgetRouteImport } from "./routes/auth/components/EmptyWidget.tsx";

const AuthIndexRouteRoute = AuthIndexRouteRouteImport.update({
  id: "/auth/",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthComponentsLoadWidgetRoute = AuthComponentsLoadWidgetRouteImport
  .update({
    id: "/auth/components/LoadWidget",
    path: "/auth/components/LoadWidget",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/auth": typeof AuthIndexRouteRoute;
  "/auth/components/LoadWidget": typeof AuthComponentsLoadWidgetRoute;
}
export interface FileRoutesByTo {
  "/auth": typeof AuthIndexRouteRoute;
  "/auth/components/LoadWidget": typeof AuthComponentsLoadWidgetRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/auth/": typeof AuthIndexRouteRoute;
  "/auth/components/LoadWidget": typeof AuthComponentsLoadWidgetRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/auth" | "/auth/components/LoadWidget";
  fileRoutesByTo: FileRoutesByTo;
  to: "/auth" | "/auth/components/LoadWidget";
  id: "__root__" | "/auth/" | "/auth/components/LoadWidget";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthIndexRouteRoute: typeof AuthIndexRouteRoute;
  AuthComponentsLoadWidgetRoute: typeof AuthComponentsLoadWidgetRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthIndexRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/components/LoadWidget": {
      id: "/auth/components/LoadWidget";
      path: "/auth/components/LoadWidget";
      fullPath: "/auth/components/LoadWidget";
      preLoaderRoute: typeof AuthComponentsLoadWidgetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthIndexRouteRoute: AuthIndexRouteRoute,
  AuthComponentsLoadWidgetRoute: AuthComponentsLoadWidgetRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
