/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TestPicklistsRouteImport } from './routes/test-picklists'
import { Route as ScouterRatingsRouteImport } from './routes/scouter-ratings'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteRouteImport } from './routes/auth/index.route'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPicklistsRoute = TestPicklistsRouteImport.update({
  id: '/test-picklists',
  path: '/test-picklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ScouterRatingsRoute = ScouterRatingsRouteImport.update({
  id: '/scouter-ratings',
  path: '/scouter-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRouteRoute = AuthIndexRouteRouteImport.update({
  id: '/auth/',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset': typeof ResetRoute
  '/scouter-ratings': typeof ScouterRatingsRoute
  '/test-picklists': typeof TestPicklistsRoute
  '/verify': typeof VerifyRoute
  '/auth': typeof AuthIndexRouteRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset': typeof ResetRoute
  '/scouter-ratings': typeof ScouterRatingsRoute
  '/test-picklists': typeof TestPicklistsRoute
  '/verify': typeof VerifyRoute
  '/auth': typeof AuthIndexRouteRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset': typeof ResetRoute
  '/scouter-ratings': typeof ScouterRatingsRoute
  '/test-picklists': typeof TestPicklistsRoute
  '/verify': typeof VerifyRoute
  '/auth/': typeof AuthIndexRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset'
    | '/scouter-ratings'
    | '/test-picklists'
    | '/verify'
    | '/auth'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset'
    | '/scouter-ratings'
    | '/test-picklists'
    | '/verify'
    | '/auth'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/reset'
    | '/scouter-ratings'
    | '/test-picklists'
    | '/verify'
    | '/auth/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetRoute: typeof ResetRoute
  ScouterRatingsRoute: typeof ScouterRatingsRoute
  TestPicklistsRoute: typeof TestPicklistsRoute
  VerifyRoute: typeof VerifyRoute
  AuthIndexRouteRoute: typeof AuthIndexRouteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-picklists': {
      id: '/test-picklists'
      path: '/test-picklists'
      fullPath: '/test-picklists'
      preLoaderRoute: typeof TestPicklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouter-ratings': {
      id: '/scouter-ratings'
      path: '/scouter-ratings'
      fullPath: '/scouter-ratings'
      preLoaderRoute: typeof ScouterRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetRoute: ResetRoute,
  ScouterRatingsRoute: ScouterRatingsRoute,
  TestPicklistsRoute: TestPicklistsRoute,
  VerifyRoute: VerifyRoute,
  AuthIndexRouteRoute: AuthIndexRouteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
