//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_list")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event: String,
    #[sea_orm(column_type = "Text")]
    pub alias: String,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    pub last_modified: i32,
    pub deleted_at: Option<i32>,
    pub inflight: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_match_data::Entity")]
    EventMatchData,
    #[sea_orm(has_many = "super::event_picklist::Entity")]
    EventPicklist,
    #[sea_orm(has_many = "super::event_picklist_entries::Entity")]
    EventPicklistEntries,
    #[sea_orm(has_many = "super::event_schedule::Entity")]
    EventSchedule,
    #[sea_orm(has_many = "super::event_team_data::Entity")]
    EventTeamData,
}

impl Related<super::event_match_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventMatchData.def()
    }
}

impl Related<super::event_picklist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventPicklist.def()
    }
}

impl Related<super::event_picklist_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventPicklistEntries.def()
    }
}

impl Related<super::event_schedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSchedule.def()
    }
}

impl Related<super::event_team_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventTeamData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
