//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_match_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub r#match: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub team: String,
    #[sea_orm(column_type = "Text")]
    pub alliance: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub data_raw: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub uid: Option<String>,
    pub timestamp: Option<i32>,
    pub last_modified: i32,
    pub deleted_at: Option<i32>,
    pub inflight: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_list::Entity",
        from = "Column::Event",
        to = "super::event_list::Column::Event",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EventList,
}

impl Related<super::event_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
