//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_picklist_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub team: String,
    pub rank: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub flags: Option<String>,
    pub last_modified: i32,
    pub deleted_at: Option<i32>,
    pub inflight: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_list::Entity",
        from = "Column::Event",
        to = "super::event_list::Column::Event",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EventList,
    #[sea_orm(
        belongs_to = "super::event_picklist::Entity",
        from = "Column::Id",
        to = "super::event_picklist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EventPicklist,
}

impl Related<super::event_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventList.def()
    }
}

impl Related<super::event_picklist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventPicklist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
