-- Initial Migration Script

-- Database Enums

do $$ 
begin
   if not exists (select 1 from pg_type where typname = 'alliance') then
      create type public.alliance as enum ('red', 'blue');
   end if;
   if not exists (select 1 from pg_type where typname = 'role') then
      create type public.role as enum ('user', 'scouter', 'lead');
   end if;
   if not exists (select 1 from pg_type where typname = 'perm') then
      create type public.perm as enum ('data.view', 'data.write', 'schedule.view', 'schedule.write', 'event.write', 'profiles.view', 'profiles.write', 'picklist.write', 'picklist.view');
   end if;
   if not exists (select 1 from pg_type where typname = 'invite_code') then
      create type public.invite_code as enum ('promote.scouter', 'promote.admin');
   end if;
   if not exists (select 1 from pg_type where typname = 'pick_type') then
      create type public.pick_type as enum ('public', 'default', 'private');
   end if;
end $$;

-- Event List

create table event_list (
   event_year integer not null,
   event_code text not null,
   alias text not null,
   date text not null,
   primary key (event_year, event_code)
);

-- Team List

create table team_list (
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   assigned_user_id text not null,
   primary key (event_year, event_code, team_key),
   foreign key (event_year, event_code)
      references event_list (event_year, event_code)
      on delete cascade
);

-- Team Data

create table team_data (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   data jsonb not null,
   user_id text not null,
   timestamp timestamp with time zone 
      not null 
      default (now() at time zone 'utc'::text),
    
   foreign key (event_year, event_code, team_key)
      references team_list (event_year, event_code, team_key)
      on delete cascade
);

create index idx_event_team
on team_data (event_year, event_code, team_key);

create index idx_team_data_jsonb
on team_data using gin (data);

-- match list

create table match_list (
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   match_key text not null,
   assigned_user_id text not null,
   primary key (event_year, event_code, team_key, match_key),
   foreign key (event_year, event_code, team_key)
      references team_list (event_year, event_code, team_key)
      on delete cascade
);

-- match data

create table match_data (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   match_key text not null,
   data jsonb not null,
   user_id text not null,
   timestamp timestamp with time zone 
      not null 
      default (now() at time zone 'utc'::text),

   foreign key (event_year, event_code)
      references event_list (event_year, event_code)
      on delete cascade,
   unique (event_year, event_code, team_key, match_key, user_id)
);

create index idx_event_team_match
on match_data (event_year, event_code, team_key, match_key);

create index idx_match_data_jsonb
on match_data using gin (data);

-- user profiles

create table if not exists user_profiles (
    uid uuid default auth.uid() primary key,
    name text default 'user' not null,
    role role default 'user' not null,
    matches integer default 0 not null,
    accuracy float default 1 not null,
    settings jsonb default '[]' not null,

    foreign key (uid)
        references auth.users (id)
        on update cascade
        on delete cascade
);

create table if not exists user_roles (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   role role not null,
   permission perm not null,

   unique (role, permission)
);

create table if not exists invite_codes (
   code text primary key,
   type invite_code not null,
   expiry timestamp with time zone
      not null
);
