-- Initial Migration Script

-- Database Enums

do $$ 
begin
   if not exists (select 1 from pg_type where typname = 'alliance') then
      create type public.alliance as enum ('red', 'blue');
   end if;
   if not exists (select 1 from pg_type where typname = 'role') then
      create type public.role as enum ('user', 'scouter', 'lead');
   end if;
   if not exists (select 1 from pg_type where typname = 'perm') then
      create type public.perm as enum ('data.view', 'data.write', 'schedule.view', 'schedule.write', 'event.write', 'profiles.view', 'profiles.write', 'picklist.write', 'picklist.view');
   end if;
   if not exists (select 1 from pg_type where typname = 'invite_code') then
      create type public.invite_code as enum ('promote.scouter', 'promote.admin');
   end if;
   if not exists (select 1 from pg_type where typname = 'pick_type') then
      create type public.pick_type as enum ('public', 'default', 'private');
   end if;
end $$;

-- Event List

create table event_list (
   event_year integer not null,
   event_code text not null,
   alias text not null,
   date text not null,
   primary key (event_year, event_code)
);

-- Team List

create table team_list (
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   assigned_user_id text not null,
   primary key (event_year, event_code, team_key),
   foreign key (event_year, event_code)
      references event_list (event_year, event_code)
      on delete cascade
);

-- Team Data

create table team_data (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   data jsonb not null,
   user_id text not null,
   timestamp timestamp with time zone 
      not null 
      default (now() at time zone 'utc'::text),
    
   foreign key (event_year, event_code, team_key)
      references team_list (event_year, event_code, team_key)
      on delete cascade
);

create index idx_event_team
on team_data (event_year, event_code, team_key);

create index idx_team_data_jsonb
on team_data using gin (data);

-- match list

create table match_list (
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   match_key text not null,
   assigned_user_id text not null,
   primary key (event_year, event_code, team_key, match_key),
   foreign key (event_year, event_code, team_key)
      references team_list (event_year, event_code, team_key)
      on delete cascade
);

-- match data

create table match_data (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_year integer not null,
   event_code text not null,
   team_key text not null,
   match_key text not null,
   data jsonb not null,
   user_id text not null,
   timestamp timestamp with time zone 
      not null 
      default (now() at time zone 'utc'::text),

   foreign key (event_year, event_code)
      references event_list (event_year, event_code)
      on delete cascade,
   unique (event_year, event_code, team_key, match_key, user_id)
);

create index idx_event_team_match
on match_data (event_year, event_code, team_key, match_key);

create index idx_match_data_jsonb
on match_data using gin (data);

-- user profiles

create table if not exists user_profiles (
    uid uuid default auth.uid() primary key,
    name text default 'user' not null,
    role role default 'user' not null,
    matches integer default 0 not null,
    accuracy float default 1 not null,
    settings jsonb default '[]' not null,

    foreign key (uid)
        references auth.users (id)
        on update cascade
        on delete cascade
);

create table if not exists user_roles (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   role role not null,
   permission perm not null,

   unique (role, permission)
);

create table if not exists invite_codes (
   code text primary key,
   type invite_code not null,
   expiry timestamp with time zone
      not null
);

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = public, pg_catalog
as $$
declare
   claims jsonb;
   user_role public.role;
begin
   select role into user_role
   from public.user_profiles
   where uid = (event->>'user_id')::text::uuid;

   claims := event->'claims';

   if user_role is not null then
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
   else
      claims := jsonb_set(claims, '{user_role}', 'null');
   end if;

   event := jsonb_set(event, '{claims}', claims);

   return event;
end;
$$;

grant usage on schema public to supabase_auth_admin;

grant execute
   on function public.custom_access_token_hook
   to supabase_auth_admin;

revoke execute
   on function public.custom_access_token_hook
   from authenticated, anon, public;

grant all
   on table user_profiles, user_roles
   to supabase_auth_admin;

create or replace function public.authorize(
   requested_permission perm
)
returns boolean as $$
declare
   bind_permissions int;
   user_role public.role;
begin
   select (auth.jwt() ->> 'user_role')::public.role
   into user_role;

   select count(*)
   into bind_permissions
   from public.user_roles
   where user_roles.permission = requested_permission
     and user_roles.role = user_role;

   return bind_permissions > 0;
end;
$$ language plpgsql stable security definer set search_path = '';

drop trigger if exists on_auth_user_created on auth.users;

create sequence if not exists user_number_seq;

create or replace function public.handle_new_user () returns trigger as $$
begin
   insert into public.user_profiles (uid, name)
   values (new.id, 'User' || upper(substring(new.id::text from '.{4}$')));
   return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger on_auth_user_created
after insert on auth.users for each row
execute procedure public.handle_new_user ();

-- picklists

create table if not exists event_picklist (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   event_year integer not null,
   event_code text not null,
   title text not null,
   picklist jsonb not null default '[]',
   uname text not null,
   uid uuid not null default auth.uid(),
   type pick_type not null default 'default',
   timestamp timestamptz not null 
      default (now() at time zone 'utc'),

   constraint event_picklist_event_list_fkey
      foreign key (event_year, event_code)
      references event_list (event_year, event_code)
      on update cascade
      on delete cascade,

   constraint event_schedule_uid_fkey
      foreign key (uid)
      references user_profiles (uid)
      on update cascade
      on delete cascade
);

-- Postgres RLS
alter table match_data enable row level security;
alter table match_list enable row level security;
alter table event_list enable row level security;
alter table team_data enable row level security;
alter table team_list enable row level security;
alter table event_picklist enable row level security;

alter table user_profiles enable row level security;
alter table user_roles enable row level security;
alter table invite_codes enable row level security;

create policy "User profiles: Allow access to user profiles"
   on user_profiles
   as permissive
   for select
   to public
   using (
      ((select auth.uid()) = uid) or
      ((select authorize('profiles.view'))) or
      (current_role = 'supabase_auth_admin')
   );

create policy "User profiles: Allow supabase_auth_admin to DELETE"
   on public.user_profiles
   for DELETE
   using (current_role = 'supabase_auth_admin');

create policy "User roles: Allow supabase_auth_admin to SELECT"
   on public.user_roles
   as permissive
   for SELECT
   using (
      (current_role = 'supabase_auth_admin') or 
      authorize('schedule.view')
   );

create policy "User roles: Allow supabase_auth_admin to DELETE"
   on public.user_roles
   for DELETE
   using (current_role = 'supabase_auth_admin');

create policy "User profiles: Enable update for supabase_auth_admin"
   on user_profiles
   as permissive
   for update
   to public
   using (
      ((select auth.role()) = 'supabase_auth_admin') 
   )
   with check (
      ((select auth.role()) = 'supabase_auth_admin') 
   );

create policy "Match list: Allow authorized delete access" 
   on match_list
   for DELETE 
   to authenticated 
   using (authorize('schedule.write'));

create policy "Match list: Allow authorized insert access" 
   on match_list
   for INSERT 
   to authenticated 
   with check (authorize('schedule.write'));

create policy "Match list: Allow authorized update access" 
   on match_list
   for UPDATE 
   to authenticated 
   using (authorize('schedule.write'))
   with check (authorize('schedule.write'));

create policy "Match list: Allow authorized select access" 
   on match_list
   for SELECT
   to authenticated
   using (authorize('schedule.view'));

create policy "Match data: Allow authorized delete access" 
   on match_data
   for DELETE
   to authenticated
   using (authorize('data.write'));

create policy "Match data: Allow authorized insert access" 
   on match_data
   for INSERT 
   to authenticated 
   with check (authorize('data.write'));

create policy "Match data: Allow authorized update access" 
   on match_data
   for UPDATE
   to authenticated
   using (authorize('data.write'))
   with check (authorize('data.write'));

create policy "Match data: Allow authorized select access" 
   on match_data
   for SELECT
   to authenticated 
   using (authorize('data.view'));

create policy "Team list: Allow authorized delete access" 
   on team_list
   for DELETE 
   to authenticated 
   using (authorize('schedule.write'));

create policy "Team list: Allow authorized insert access" 
   on team_list
   for INSERT 
   to authenticated 
   with check (authorize('schedule.write'));

create policy "Team list: Allow authorized update access" 
   on team_list
   for UPDATE 
   to authenticated 
   using (authorize('schedule.write'))
   with check (authorize('schedule.write'));

create policy "Team list: Allow authorized select access" 
   on team_list
   for SELECT
   to authenticated
   using (authorize('schedule.view'));

create policy "Team data: Allow authorized delete access (data)" 
   on team_data
   for DELETE
   to authenticated
   using (authorize('data.write'));

create policy "Team data: Allow authorized update access (data)" 
   on team_data
   for UPDATE
   to authenticated
   using (authorize('data.write'))
   with check (authorize('data.write'));

create policy "Team data: Allow authorized insert access (data)" 
   on team_data
   for INSERT 
   to authenticated 
   with check (authorize('data.write'));

create policy "Team data: Allow authorized select access (data)" 
   on team_data
   for SELECT
   to authenticated 
   using (authorize('data.view'));

create policy "Event list: Allow authorized delete access (event)" 
   on event_list
   for DELETE
   to public
   using (authorize('event.write'));

create policy "Event list: Allow authorized insert access (event)" 
   on event_list
   for INSERT
   to public
   with check (authorize('event.write'));

create policy "Event list: Allow free select access" 
   on event_list
   for SELECT
   to public
   using (true);

create policy "Event picklist: Enable select for users based on uid"
   on event_picklist
   as permissive
   for SELECT
   to public
   using (
      ((select auth.uid()) = uid) or
      (type = 'public') or
      (authorize('picklist.view') and not (type = 'private'))
   );

create policy "Event picklist: Enable update for users based on uid"
   on event_picklist
   as permissive
   for UPDATE
   to public
   using (
      ((select auth.uid()) = uid) or
      (authorize('picklist.view') and not (type = 'private'))
   )
   with check (
      ((select auth.uid()) = uid) or
      (authorize('picklist.view') and not (type = 'private'))
   );

create policy "Event picklist: Enable insert for users based on uid"
   on event_picklist
   as permissive
   for INSERT
   to public
   with check (
      ((select auth.uid()) = uid) or
      (authorize('picklist.view') and not (type = 'private'))
   );

create policy "Event picklist: Enable delete for users based on uid"
   on event_picklist
   as permissive
   for DELETE
   to public
   using (
      ((select auth.uid()) = uid) or 
      (authorize('picklist.view') and not (type = 'private'))
   );

create policy "Invite codes: Enable insert for users based on permissions"
   on invite_codes
   as permissive
   for INSERT
   to public
   with check (
      authorize('profiles.write')
   );

insert into user_roles (role, permission) values ('lead', 'data.view');
insert into user_roles (role, permission) values ('lead', 'data.write');
insert into user_roles (role, permission) values ('lead', 'schedule.view');
insert into user_roles (role, permission) values ('lead', 'schedule.write');
insert into user_roles (role, permission) values ('lead', 'event.write');
insert into user_roles (role, permission) values ('lead', 'profiles.view');
insert into user_roles (role, permission) values ('lead', 'profiles.write');
insert into user_roles (role, permission) values ('lead', 'picklist.view');
insert into user_roles (role, permission) values ('lead', 'picklist.write');

insert into user_roles (role, permission) values ('scouter', 'data.view');
insert into user_roles (role, permission) values ('scouter', 'data.write');
insert into user_roles (role, permission) values ('scouter', 'picklist.view');
insert into user_roles (role, permission) values ('scouter', 'schedule.view');

insert into user_roles (role, permission) values ('user', 'data.view');
insert into user_roles (role, permission) values ('user', 'schedule.view');
